server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.0.103:3100/loki/api/v1/push


# =======================================================================
# ИСТОЧНИК 1: ЛОГИ ПРИЛОЖЕНИЯ
# =======================================================================
scrape_configs:
  - job_name: application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application-logs
          host: production-server
          source: APPLICATION
          __path__: /app/logs/log*.json
    
    pipeline_stages:
      # Парсинг текстовой строки
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} [+-]\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<message>.*)$'
      
      # Нормализация уровня
      - template:
          source: level_normalized
          template: '{{ if eq .level "Warning" }}WARN{{ else if eq .level "Information" }}INFO{{ else if eq .level "Error" }}ERROR{{ else if eq .level "Debug" }}DEBUG{{ else }}{{ .level | ToUpper }}{{ end }}'
      
      # Добавляем метку
      - labels:
          level: level_normalized
      
      # Форматируем время
      - template:
          source: time_short
          template: '{{ regexReplaceAll "(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}).*" .timestamp "${1}" }}'
      
      # Создаём единый формат
      - template:
          source: output
          template: '[{{ .time_short }}] [{{ .level_normalized }}] [APPLICATION] {{ .message }}'
      
      # Устанавливаем как вывод
      - output:
          source: output
      
      # Устанавливаем время
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000 -07:00'
  - job_name: docker-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker-logs
        __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:

    - json:
        expressions:
          stream: stream
          attrs: attrs
          tag: attrs.tag

    - regex:
        expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
        source: "tag"

    - labels:
        tag:
        image_name:
        container_name:
